replicaCount: 1

image:
  repository: harbor.i2cv.io/cosmichorizon/farm-tracks
  pullPolicy: Always
  tag: ""

imagePullSecrets:
  - name: s-hxl2n
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  portWeb: 80
  portApi: 8000

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "4"
    memory: "8Gi"

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/farm-tracks)$ $1/ permanent;
  hosts:
    - host: farmtrack.local
      paths:
        # Route API traffic to the backend container port
        - path: /farm-tracks(/)(api/.*)
          pathType: ImplementationSpecific
          backendPort: 8000
        # Route all other web traffic to the frontend container port
        - path: /farm-tracks(/|$)(.*)
          pathType: ImplementationSpecific
          backendPort: 80
  tls: []
