apiVersion: v1
kind: Service
metadata:
  name: {{ include "farm-tracks.fullname" . }}
  labels:
    {{- include "farm-tracks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portWeb }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.portApi }}
    - port: {{ .Values.service.portApi }}
      targetPort: api
      protocol: TCP
      name: api
    {{- end }}
  selector:
    {{- include "farm-tracks.selectorLabels" . | nindent 4 }}
